name: 'Aqua Security Tracee Start'
description: 'Start Runtime Security and Forensics using eBPF'
author: 'Aqua Security'

runs:
  using: 'composite'
  steps:
  - shell: bash
    run: |
      docker pull simar7/tracee:latest
      docker run --name tracee-profiler --rm --privileged \
      -v /proc:/proc -v /boot:/boot -v /lib/modules/:/lib/modules/:ro \
      -v /usr/src:/usr/src:ro -v $(pwd):/tmp/tracee simar7/tracee:latest \
      trace --output out-file:"/tmp/tracee/tracee.stdout.log" \
      --capture exec --capture profile &