name: Start Tracee Background Scan
on:
  push:
    branches:
    - "*"

jobs:
  Tracee-Scan:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
    - name: Start Tracee profiling in background
      uses: simar7/tracee-action-start@main
      with:
        workdir: "/tmp/tracee"

    - name: Check if tracee was succesfully started
      run: |
        sleep 30
        docker images -a
        docker ps -a
        docker logs tracee-profiler | head
        docker inspect tracee-profiler
        ls -lrRth /tmp/tracee